import { IEmployee } from '@/models/employee';

export const MOCKED_USERS: IEmployee[] = [
  {
    id: '1',
    name: 'Daniel',
    surname: 'Blane',
    birthDate: '10.02.2003',
    phone: '+375 29 173 9141',
    email: 'danielblane@gmail.com',
    username: '@danielblane',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Lead',
    active: true,
  },
  {
    id: '2',
    name: 'Vitaly',
    surname: 'Olhov',
    birthDate: '02.10.2003',
    phone: '+375 29 173 9141',
    email: 'vitalyableat@gmail.com',
    username: '@vitalyableat',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Junior',
    active: true,
  },
  {
    id: '3',
    name: 'Daniel',
    surname: 'Blane',
    birthDate: '10.02.2003',
    phone: '+375 29 173 9141',
    email: 'danielblane@gmail.com',
    username: '@danielblane',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Lead',
    active: true,
  },
  {
    id: '4',
    name: 'Vitaly',
    surname: 'Olhov',
    birthDate: '02.10.2003',
    phone: '+375 29 173 9141',
    email: 'vitalyableat@gmail.com',
    username: '@vitalyableat',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Junior',
    active: true,
  },
  {
    id: '5',
    name: 'Daniel',
    surname: 'Blane',
    birthDate: '10.02.2003',
    phone: '+375 29 173 9141',
    email: 'danielblane@gmail.com',
    username: '@danielblane',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Lead',
    active: true,
  },
  {
    id: '6',
    name: 'Vitaly',
    surname: 'Olhov',
    birthDate: '02.10.2003',
    phone: '+375 29 173 9141',
    email: 'vitalyableat@gmail.com',
    username: '@vitalyableat',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Junior',
    active: true,
  },
  {
    id: '7',
    name: 'Daniel',
    surname: 'Blane',
    birthDate: '10.02.2003',
    phone: '+375 29 173 9141',
    email: 'danielblane@gmail.com',
    username: '@danielblane',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Lead',
    active: true,
  },
  {
    id: '8',
    name: 'Vitaly',
    surname: 'Olhov',
    birthDate: '02.10.2003',
    phone: '+375 29 173 9141',
    email: 'vitalyableat@gmail.com',
    username: '@vitalyableat',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Junior',
    active: true,
  },
  {
    id: '9',
    name: 'Daniel',
    surname: 'Blane',
    birthDate: '10.02.2003',
    phone: '+375 29 173 9141',
    email: 'danielblane@gmail.com',
    username: '@danielblane',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Lead',
    active: true,
  },
  {
    id: '10',
    name: 'Vitaly',
    surname: 'Olhov',
    birthDate: '02.10.2003',
    phone: '+375 29 173 9141',
    email: 'vitalyableat@gmail.com',
    username: '@vitalyableat',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Junior',
    active: true,
  },
  {
    id: '11',
    name: 'Daniel',
    surname: 'Blane',
    birthDate: '10.02.2003',
    phone: '+375 29 173 9141',
    email: 'danielblane@gmail.com',
    username: '@danielblane',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Lead',
    active: true,
  },
  {
    id: '12',
    name: 'Vitaly',
    surname: 'Olhov',
    birthDate: '02.10.2003',
    phone: '+375 29 173 9141',
    email: 'vitalyableat@gmail.com',
    username: '@vitalyableat',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Junior',
    active: true,
  },
  {
    id: '13',
    name: 'Daniel',
    surname: 'Blane',
    birthDate: '10.02.2003',
    phone: '+375 29 173 9141',
    email: 'danielblane@gmail.com',
    username: '@danielblane',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Lead',
    active: true,
  },
  {
    id: '14',
    name: 'Vitaly',
    surname: 'Olhov',
    birthDate: '02.10.2003',
    phone: '+375 29 173 9141',
    email: 'vitalyableat@gmail.com',
    username: '@vitalyableat',
    startDate: '01.01.2022',
    position: 'React Developer',
    level: 'Junior',
    active: true,
  },
];
